<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyName>naja</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Naja.CodeGen\Naja.CodeGen.csproj" />
		<ProjectReference Include="..\Naja.Inference\Naja.Inference.csproj" />
		<ProjectReference Include="..\Naja.Lexer\Naja.Lexer.csproj" />
		<ProjectReference Include="..\Naja.Parser\Naja.Parser.csproj" />
		<ProjectReference Include="..\Naja.Semantics\Naja.Semantics.csproj" />
	</ItemGroup>
</Project>