namespace Naja.StdLib;

/// <summary>
/// Python 'signal' module emulation.
/// Provides signal handling constants for Windows and Unix.
/// 
/// Windows-specific signals:
/// - CTRL_C_EVENT: Ctrl+C console event (value 0)
/// - CTRL_BREAK_EVENT: Ctrl+Break console event (value 1)
/// 
/// Common signals:
/// - SIGTERM: Termination signal (value 15)
/// - SIGINT: Interrupt signal (Ctrl+C) (value 2)
/// </summary>
public sealed class NajaSignal
{
    public static readonly NajaSignal Instance = new();

    // ── Standard Unix signals ─────────────────────────────────────────────

    /// <summary>
    /// Termination signal (SIGTERM = 15)
    /// Requested termination of the process
    /// </summary>
    public long SIGTERM => 15;

    /// <summary>
    /// Interrupt signal (SIGINT = 2)
    /// Typically generated by Ctrl+C
    /// </summary>
    public long SIGINT => 2;

    // ── Windows console control events ───────────────────────────────────

    /// <summary>
    /// Windows Ctrl+C event (value 0)
    /// Can be sent to a process group on Windows via os.kill()
    /// </summary>
    public long CTRL_C_EVENT => 0;

    /// <summary>
    /// Windows Ctrl+Break event (value 1)
    /// Can be sent to a process group on Windows via os.kill()
    /// </summary>
    public long CTRL_BREAK_EVENT => 1;

    // ── Other common signals (for reference) ──────────────────────────────

    /// <summary>
    /// Hangup detected on controlling terminal or death of controlling process (SIGHUP = 1)
    /// </summary>
    public long SIGHUP => 1;

    /// <summary>
    /// Illegal instruction (SIGILL = 4)
    /// </summary>
    public long SIGILL => 4;

    /// <summary>
    /// Abort signal (SIGABRT = 6)
    /// </summary>
    public long SIGABRT => 6;

    /// <summary>
    /// Floating point exception (SIGFPE = 8)
    /// </summary>
    public long SIGFPE => 8;

    /// <summary>
    /// Kill signal (SIGKILL = 9)
    /// Cannot be caught or ignored
    /// </summary>
    public long SIGKILL => 9;

    /// <summary>
    /// Segmentation violation (SIGSEGV = 11)
    /// </summary>
    public long SIGSEGV => 11;

    /// <summary>
    /// Broken pipe (SIGPIPE = 13)
    /// </summary>
    public long SIGPIPE => 13;

    /// <summary>
    /// User-defined signal 1 (SIGUSR1 = 10)
    /// </summary>
    public long SIGUSR1 => 10;

    /// <summary>
    /// User-defined signal 2 (SIGUSR2 = 12)
    /// </summary>
    public long SIGUSR2 => 12;

    /// <summary>
    /// Stopped (signal) (SIGSTOP = 19)
    /// Cannot be caught or ignored
    /// </summary>
    public long SIGSTOP => 19;

    /// <summary>
    /// Stopped (user) (SIGTSTP = 20)
    /// </summary>
    public long SIGTSTP => 20;

    /// <summary>
    /// Continued (SIGCONT = 18)
    /// </summary>
    public long SIGCONT => 18;

    /// <summary>
    /// Child process exited or stopped (SIGCHLD = 17)
    /// </summary>
    public long SIGCHLD => 17;

    /// <summary>
    /// Alarm clock (SIGALRM = 14)
    /// </summary>
    public long SIGALRM => 14;
}
